# general
seed: 42
workers: 6
dataset_dir: "./datasets"

# train options
batch_size: 256
image_size: 224
start_epoch: 0
epochs: 1000
dataset: "ImageNet-10" # CIFAR-10 / CIFAR-100 /  / ImageNet-10 / ImageNet-dogs / tiny-ImageNet
writer_log_dir: ".runs"

# model options
resnet: "ResNet34" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/tmp"
reload: False

